
export const ADD_COMPONENT = 'ADD_COMPONENT';
export const REFRESH_COMPONENT = 'REFRESH_COMPONENT';
export const REFRESH_COMPONENTS = 'REFRESH_COMPONENTS';
export const REMOVE_COMPONENT = 'REMOVE_COMPONENT';